# Generated by Django 6.0.1 on 2026-02-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
